// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Pokemon struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	Abilities   *string `json:"abilities,omitempty"`
	Type        *string `json:"type,omitempty"`
}

type PokemonInput struct {
	ID          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	Abilities   *string `json:"abilities,omitempty"`
	Type        *string `json:"type,omitempty"`
}

type Query struct {
}
